language: php
php:
- 'hhvm'
- '5.6'
- '5.5'
- '5.4'
install:
  - composer install --dev --no-scripts
script:
  - ./vendor/bin/phpcs --standard=psr2 --ignore=vendor -n .
  - phpunit --coverage-clover build/logs/clover.xml
